# Introduction to Python

### Python Basics
___

1. `areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]`
  - Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
  - Change "living room" to "chill zone"
  - Extend the list `["poolhouse", 24.5]` to the end of the areas list. Store the resulting list as areas_1.
  - Extend areas_1 by adding data on your garage. Add the string `"garage"` and float `15.45`. Name the resulting list areas_2.
  - Delete the last two entry in the list (string `"garage"` and float `15.45`)
  - Copy the entire list `areas_2` in `areas_3`, `areas_4` and `area_5` using three diffent ways.

In [17]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas[-1] = 10.50
print(areas)
areas[4] = "chill zone"
print(areas)
areas_1 = areas + ["poolhouse", 24.5]
print(areas_1)
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)
del(areas_2[-1])
print(areas_2)
del(areas_2[-1])
print(areas_2)
areas_3 = list(areas_2)
print(areas_3)
areas_4 = areas_2[:]
print(areas_4)
areas_5 = areas_2.copy()
print(areas_5)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage']
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]


2. `first = [11.25, 18.0, 20.0]`;
`second = [10.75, 9.50, 20.0]`
  - Concatenate both the list : `full`
  - Print the index of 20.0
  - Print out how often 20.0 appears
  - Append 24.5 and 15.4
  - Reverse the list
  - Sort the list `full` in both ascending and descending order in place
  - Sort the list `full` in both ascending and descending order : `full_a` and `full_d`

### Using `append` and passing a list will add the list as single object. But using `extend` and passing a list will add the values of the list in the preious list

In [45]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50, 20.0]
full = first + second
print(full.index(20))
print(full.count(20))
full.append(24.5)
full.append(15.4)
print(full)
full.append([24.5, 15.4])
print(full)
del(full[-1])
print(full)
full.extend([24.5, 15.4])
print(full)
full.reverse()
print(full)
full.sort()
print(full)
full.sort(reverse=True)
print(full)
full_a = sorted(full)
print(full_a)
full_d = sorted(full, reverse=True)
print(full_d)

2
2
[11.25, 18.0, 20.0, 10.75, 9.5, 20.0, 24.5, 15.4]
[11.25, 18.0, 20.0, 10.75, 9.5, 20.0, 24.5, 15.4, [24.5, 15.4]]
[11.25, 18.0, 20.0, 10.75, 9.5, 20.0, 24.5, 15.4]
[11.25, 18.0, 20.0, 10.75, 9.5, 20.0, 24.5, 15.4, 24.5, 15.4]
[15.4, 24.5, 15.4, 24.5, 20.0, 9.5, 10.75, 20.0, 18.0, 11.25]
[9.5, 10.75, 11.25, 15.4, 15.4, 18.0, 20.0, 20.0, 24.5, 24.5]
[24.5, 24.5, 20.0, 20.0, 18.0, 15.4, 15.4, 11.25, 10.75, 9.5]
[9.5, 10.75, 11.25, 15.4, 15.4, 18.0, 20.0, 20.0, 24.5, 24.5]
[24.5, 24.5, 20.0, 20.0, 18.0, 15.4, 15.4, 11.25, 10.75, 9.5]


3. `place = "poolhouse"`
  - Convert each letters into uppercase
  - Count the number of 'o' in the string

In [50]:
place = "poolhouse"
place_upper = place.upper()
print(place_upper)
print(place.count('o'))

POOLHOUSE
3


4. radius `r = 0.43`
  - Calculate the area and circumference of the circle: `area`, `circumference`
  - Round both the result upto 2 decimal points: `area_r`, `circumference_2`

In [62]:
import math
r = 0.43
area = math.pi  * r * r
print(area)
circumference = 2 * math.pi * r
print(circumference)
print(round(area,2))
print(round(circumference,2))

0.5808804816487527
2.701769682087222
0.58
2.7


5. `baseball = [180, 215, 210, 210, 188, 176, 209, 200]`
  - Create a numpy array from baseball: `np_baseball`
  - Print out type of np_baseball
  - Add 5 to all the elements in np_baseball
  - Print out the element at index 5
  - Print out sub-array of np_baseball: index 2 up to and including index 4

In [69]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball + 5)
print(np_baseball[5])
print(np_baseball[2:5])

<class 'numpy.ndarray'>
[185 220 215 215 193 181 214 205]
176
[210 210 188]


6. `height`(inch), `weight`(lb) is available as a regular list.
  - Create a numpy array: np_height_in
  - Convert np_height_in to metre: np_height_m by multiplying 0.0254
  - Calculate BMI : np_bmi : weight(kg) / height(m)^2 : ld to kg = multiply by 0.453592
  - Print out a numpy array with the BMIs of all baseball players whose BMI is below 21.

```Python
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\baseball.csv")
height = list(df['Height']) 
weight = list(df['Weight'])
```

In [80]:
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\baseball.csv")
height = list(df['Height']) 
weight = list(df['Weight'])
np_height_in = np.array(height)
np_weight_lb = np.array(weight)
np_height_m = np_height_in * 0.0254
np_weight_kg = np_weight_lb * 0.453592
bmi = np_weight_kg / (np_height_m ** 2)
print(bmi)
bmi_less_than_21 = bmi[bmi<21]
print(bmi_less_than_21)
print(len(bmi_less_than_21))

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]
11


7. numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.
  - Output of `np.array([True, 1, 2]) + np.array([3, 4, False])`?

In [81]:
print(np.array([True, 1, 2]) + np.array([3, 4, False]))

[4 5 2]


8. `baseball = [[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]` is available as list of lists.
  - Create a 2D numpy array from baseball: np_baseball_s
  - Print the type and dimension of np_baseball

In [83]:
np_baseball = np.array([[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]])
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


9. `np_baseball` is available as ndarray
  - Print out the 50th row of np_baseball
  - Select the entire second column of np_baseball: np_weight_lb
  - Print out height of 124th player
  - Create a numpy array with two values: 0.0254, 0.453592: `conversion`.
  - Calculate the bmi of each player : bmi = weight(in kg) / height(in m) ^ 2
  - Calculate the mean, median and standard deviation of height
  - Calculate the correlation coefficient height and weight
  
```Python
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\baseball.csv")
baseball = df[['Height','Weight']]
np_baseball = baseball.values
```

In [108]:
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\baseball.csv")
baseball = df[['Height','Weight']]
np_baseball = baseball.values
print(np_baseball.shape)
print(np_baseball[50])
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)
print(len(np_weight_lb))
print(np_baseball[125,0])
conversion = np.array([0.0254, 0.453952])
np_baseball_converted = np_baseball * conversion
bmi = np_baseball_converted[:,1]/(np_baseball_converted[:,0]**2)
print(bmi)
print(np.mean(np_baseball[:,0]))
print(np.median(np_baseball[:,0]))
print(np.std(np_baseball[:,0]))

(1015, 2)
[ 73 200]
[180 215 210 ... 205 190 195]
1015
73
[23.12871828 27.62596906 28.50340886 ... 25.64329538 23.76695669
 25.74728212]
73.6896551724138
74.0
2.312791881046546


10. **Show that the median height of goalkeepers is higher than that of other players on the soccer field.**  The first list, `positions`, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, `heights`, contains integers representing the height of the player in cm.

```Python
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\fifa.csv")
height = list(df['height'])
position = list(df['position'])
```

In [134]:
import pandas as pd
df = pd.read_csv("C:\\Users\\saifs\\Desktop\\data_science\\datasets\\fifa.csv")
print(df.columns)
height = list(df[' height'])
position = list(df[' position'])
np_position = np.array(position)
np_height = np.array(height)
print(len(np_position))
print(np_height)
print(np_position)
#print(np_position[np_position == ' GK'])
goalkeeper = np_height[np_position == ' GK']
rest_players = np_height[np_position != 'GK']
print(len(goalkeeper))
print(np.median(goalkeeper))
print(np.median(rest_players))

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')
8847
[191 184 185 ... 183 179 179]
[' GK' ' M' ' A' ... ' D' ' D' ' M']
930
188.0
182.0
