In [11]:
import numpy as np
a1 = np.arange(0,6)
a2 = np.arange(6,12)
a3 = a1 + a2
a4 = a2 - a1
print(a1)
print(a2)
print(a3)
print(a4)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[6 6 6 6 6 6]


In [12]:
a1.ndim

1

In [13]:
a1.shape

(6,)

In [33]:
a5 = np.arange(0,6).reshape(3,2)
a5

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
a6 = np.arange(0,36).reshape(3,12)
a6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [38]:
a7 = np.hstack((a5,a6))
a7

array([[ 0,  1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 2,  3, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 4,  5, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [46]:
a8 = np.hsplit(a7, 2)
print(a8[1])
a8[1].sum(axis=1)

[[ 5  6  7  8  9 10 11]
 [17 18 19 20 21 22 23]
 [29 30 31 32 33 34 35]]


array([ 56, 140, 224])

In [51]:
a10 = np.vsplit(a5,3)
a10[0]

array([[0, 1]])

In [87]:
a11 = np.linspace(0.1,10.0,100).reshape(10,10)
a11

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [97]:
a12 = np.arange(10,16).reshape(3,2)
print(a12)
a13 = np.sqrt(a12)
print(a13)
a14 = a13 * a13
print(a14)
a12 == a14

[[10 11]
 [12 13]
 [14 15]]
[[3.16227766 3.31662479]
 [3.46410162 3.60555128]
 [3.74165739 3.87298335]]
[[10. 11.]
 [12. 13.]
 [14. 15.]]


array([[False,  True],
       [False, False],
       [ True, False]])

In [110]:
a16 = np.arange(20,26).reshape(3,2)
print(a16)
for x in np.nditer(a16, order = 'F', op_flags=['readwrite']):
    x[...] = x*x
a16

a17 = np.arange(20,26).reshape(3,2)
a18 = a17*a17
a18

[[20 21]
 [22 23]
 [24 25]]


array([[400, 441],
       [484, 529],
       [576, 625]])