In [1]:
import numpy as np
a1 = np.arange(0,6)
a2 = np.arange(6,12)
a3 = a1 + a2
a4 = a2 - a1
print(a1)
print(a2)
print(a3)
print(a4)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[6 6 6 6 6 6]


In [2]:
a1.ndim

1

In [3]:
a1.shape

(6,)

In [4]:
a5 = np.arange(0,6).reshape(3,2)
a5

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a6 = np.arange(0,36).reshape(3,12)
a6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [6]:
a7 = np.hstack((a5,a6))
a7

array([[ 0,  1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 2,  3, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 4,  5, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [7]:
a8 = np.hsplit(a7, 2)
print(a8[1])
a8[1].sum(axis=1)

[[ 5  6  7  8  9 10 11]
 [17 18 19 20 21 22 23]
 [29 30 31 32 33 34 35]]


array([ 56, 140, 224])

In [12]:
a10 = np.vsplit(a5,3)
a10[0]

array([[0, 1]])

In [9]:
a11 = np.linspace(0.1,10.0,100).reshape(10,10)
a11

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [22]:
new = np.linspace(1,100, 100, dtype=int).reshape(10,10)
new

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [10]:
a12 = np.arange(10,16).reshape(3,2)
print(a12)
a13 = np.sqrt(a12)
print(a13)
a14 = a13 * a13
print(a14)
a12 == a14

[[10 11]
 [12 13]
 [14 15]]
[[3.16227766 3.31662479]
 [3.46410162 3.60555128]
 [3.74165739 3.87298335]]
[[10. 11.]
 [12. 13.]
 [14. 15.]]


array([[False,  True],
       [False, False],
       [ True, False]])

* By default, the `nditer` treats the input operand as a read-only object. To be able to modify the array elements, you must specify either read-write or write-only mode using the ‘readwrite’ or ‘writeonly’ per-operand flags.

* The order 'C' first traverse row by row, while 'F' traverse column by column.

In [35]:
a16 = np.arange(20,26).reshape(3,2)
print(a16)
for x in np.nditer(a16, order = 'F', op_flags=['readwrite']):
    x[...] = x*x
a16

[[20 21]
 [22 23]
 [24 25]]


array([[400, 441],
       [484, 529],
       [576, 625]])

In [37]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a, order = 'C'):
    print(x, end=' ')

0 1 2 3 4 5 

In [36]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a, order='F'):
    print(x, end=' ')

0 3 1 4 2 5 

### Fancy Indexing

In [43]:
arr = np.empty((8,3)) # gives ndarry with uninitialized random values
arr

array([[6.23042070e-307, 8.90092016e-307, 6.89805830e-307],
       [9.34602321e-307, 6.23054972e-307, 8.45593934e-307],
       [7.56593017e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [9.34605037e-307, 6.23059726e-307, 1.24612353e-306],
       [6.89804133e-307, 8.45610231e-307, 9.34601642e-307],
       [8.90092016e-307, 1.86919378e-306, 8.45559303e-307],
       [1.06811422e-306, 1.05694828e-307, 2.22522596e-306]])

In [47]:
for i in range(len(arr)):
    arr[i] = i
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

In [53]:
# select out a subset of the rows in a particular order
# simply pass a list or ndarray of integers specifying the desired order
order_l = np.array([4,1,7])
print(arr[order_l], end = '\n\n')
print(arr[[4,1,5]])

[[4. 4. 4.]
 [1. 1. 1.]
 [7. 7. 7.]]

[[4. 4. 4.]
 [1. 1. 1.]
 [5. 5. 5.]]


In [58]:
arr = np.arange(48).reshape(8,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [59]:
arr[[4,2,6,1],[1,3,4,2]] # return value at index (4,1), (2,3), (6,4), (1,2)

array([25, 15, 40,  8])

In [60]:
arr[[4,6,1,3]]

array([[24, 25, 26, 27, 28, 29],
       [36, 37, 38, 39, 40, 41],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [61]:
arr[[4,6,1,3]][:, [2,5,0]]

array([[26, 29, 24],
       [38, 41, 36],
       [ 8, 11,  6],
       [20, 23, 18]])

In [63]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
arr_transpose = arr.T
arr_transpose

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [68]:
# Calculate the inner dot product of arr
inner_dot = np.dot(arr.T,arr) # arr has shape of (6,4) and its transpose has (4,6)
inner_dot # (4,6) . (6,4) = (4,4)

array([[ 880,  940, 1000, 1060],
       [ 940, 1006, 1072, 1138],
       [1000, 1072, 1144, 1216],
       [1060, 1138, 1216, 1294]])

In [78]:
arr_q = np.random.randn(9)
arr_q

array([-0.03741036,  1.20781182, -0.44326041,  0.19526278,  1.90747271,
        1.51464031,  0.11646844, -0.42836956,  0.7788343 ])

In [80]:
sum_arr = np.sum(arr_q)
sum_arr

4.811450047396927

In [83]:
arr = np.arange(5)
sq_arr = np.sqrt(arr)
sq_arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [84]:
exp_arr = np.exp(arr)
exp_arr

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [95]:
arr_random = 3 * np.random.randn(5) + 5
print(arr_random)

[1.51819529 5.63190378 4.32893405 6.14329188 7.16740443]


In [96]:
remain, whole = np.modf(arr_random)

In [97]:
print(remain)
print(whole)

[0.51819529 0.63190378 0.32893405 0.14329188 0.16740443]
[1. 5. 4. 6. 7.]


In [112]:
points = np.arange(-1,2)

In [113]:
points

array([-1,  0,  1])

In [114]:
grid = np.meshgrid(points, points)

In [115]:
grid

[array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]), array([[-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]])]

In [119]:
arr = np.random.randn(16).reshape(4,4)

In [120]:
arr

array([[-0.97472113,  1.98461366,  0.11634539, -1.52254176],
       [-0.3850841 ,  0.27944744, -0.03255042,  0.99858331],
       [ 0.90434137,  0.82496763,  0.82985534, -0.16530618],
       [ 0.79947025,  0.76100156,  1.15916103,  2.01085028]])

In [121]:
arr > 0

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [127]:
new_arr = np.where(arr > 0, 2, 4) # where the condition satisfies, it replaces with x, else y
new_arr

array([[4, 2, 2, 4],
       [4, 2, 4, 2],
       [2, 2, 2, 4],
       [2, 2, 2, 2]])

In [128]:
arr = np.random.randn(5)

In [129]:
np.sum(arr)

1.6129509157765138

In [131]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [134]:
arr.sum(axis = 1) # axis 1 means calculating sum of values in a row, or across columns

array([ 6, 22, 38, 54, 70])

In [135]:
arr.sum(axis = 0) # axis 0 means calculating sum of values in a column, or across rows

array([40, 45, 50, 55])

In [136]:
arr.cumsum(1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70]], dtype=int32)

In [138]:
arr.cumsum(0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)

In [139]:
arr.mean()

9.5

In [140]:
arr.mean(1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [141]:
arr.mean(0)

array([ 8.,  9., 10., 11.])

In [145]:
arr.cumprod(1) # cummulative product

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760],
       [   16,   272,  4896, 93024]], dtype=int32)

In [146]:
arr.cumprod(0)

array([[    0,     1,     2,     3],
       [    0,     5,    12,    21],
       [    0,    45,   120,   231],
       [    0,   585,  1680,  3465],
       [    0,  9945, 30240, 65835]], dtype=int32)

In [147]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [150]:
arr = np.random.randn(3,4)
arr

array([[ 1.52211274,  0.81981452, -2.00426861,  1.03112411],
       [ 2.34810333,  1.2783263 ,  0.27057092, -0.01662775],
       [-0.28957404, -0.33111679, -0.72825613, -0.27606207]])

In [151]:
arr.sort() # return sorted rows
arr

array([[-2.00426861,  0.81981452,  1.03112411,  1.52211274],
       [-0.01662775,  0.27057092,  1.2783263 ,  2.34810333],
       [-0.72825613, -0.33111679, -0.28957404, -0.27606207]])

In [154]:
arr = np.random.randn(4,3)
arr

array([[-1.40473112, -0.06483763,  1.41738982],
       [ 0.78235657, -2.20061219,  1.3397195 ],
       [ 1.00822245, -0.05469932,  0.18330413],
       [-2.04550025,  0.41831544,  0.60687758]])

In [156]:
arr.sort(axis=0)
arr

array([[-2.04550025, -2.20061219,  0.18330413],
       [-1.40473112, -0.06483763,  0.60687758],
       [ 0.78235657, -0.05469932,  1.3397195 ],
       [ 1.00822245,  0.41831544,  1.41738982]])

In [158]:
x = np.arange(6).reshape(2,3)
print(x)
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [160]:
z = np.dot(x,y) 
print(z)

[[15 18 21]
 [42 54 66]]


In [163]:
x.dot(y) # equivalent to np.dot(x,y) and it also does not manipulate the value of x

array([[15, 18, 21],
       [42, 54, 66]])

In [164]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [183]:
import numpy.linalg

In [184]:
x = np.random.randint(0,100,9).reshape(3,3)
x

array([[17, 41,  2],
       [79, 83, 30],
       [86, 15, 41]])

In [185]:
inv(x)

array([[ 0.26188365, -0.14641717,  0.0943597 ],
       [-0.05844271,  0.04655906, -0.03121674],
       [-0.52793544,  0.29008514, -0.16211422]])

In [186]:
x.dot(inv(x))

array([[ 1.00000000e+00, -6.66133815e-16,  2.77555756e-16],
       [ 2.22044605e-16,  1.00000000e+00,  8.32667268e-16],
       [-9.99200722e-16, -6.66133815e-16,  1.00000000e+00]])

In [190]:
x.trace() # sum of diagonal elements

141

In [193]:
numpy.linalg.det(x)

11275.999999999982

### See all the functions included in numpy.linalg module

In [198]:
?numpy.linalg

In [201]:
x = np.random.normal(size=(4,4))
x

array([[-0.7117305 ,  0.42777571, -0.72806155,  0.64480508],
       [ 1.07229089, -0.27346545,  0.81374452,  1.1417699 ],
       [-1.25827962, -0.09004432,  2.39562851, -0.96713526],
       [-0.78214205,  1.48377667,  0.1579026 ,  0.03631058]])

In [202]:
x.mean()

0.21019660658889805

### Simulating random walk

In [205]:
position = [0]
for i in range(10):
    x = position[i] + np.random.randint(5)
    position.append(x)
position

[0, 2, 3, 3, 5, 7, 7, 8, 12, 13, 14]

In [209]:
x = np.random.randint(0,5,20)
x.cumsum()

array([ 1,  1,  3,  4,  8,  8,  8,  9, 11, 15, 15, 19, 23, 23, 23, 26, 28,
       30, 34, 35], dtype=int32)