Extended operator works with real instance of the object. 
Here, `b += [4,5]` extends real object, means object `a` because `b` was alias of `a`.
But in `c = c + [6,7]`, the expression is first evaluated. Since, `c` is also an alias of `a` and `b += [4,5]` has already extended `a` into `[1, 2, 3, 4, 5]`, so the value of `c` will also be `[1, 2, 3, 4, 5]`. Now, the value of the expression `c + [6,7]` will be `[1, 2, 3, 4, 5, 6, 7]` for which a new instance is created and then the instance is assigned back only to the variable `c` and not in `b` or `a`.

In [3]:
a = [1,2,3]
b = a
c = a
b += [4,5]
c = c + [6,7]
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7]


In [4]:
a = [1,2,3]
b = a
c = a
b = b + [4,5]
c = c + [6,7]
print(a)
print(b)
print(c)

[1, 2, 3]
[1, 2, 3, 4, 5]
[1, 2, 3, 6, 7]


In [7]:
import numpy as np
x = np.array([[-1],[-2]])
y = np.array([[-3,-4]])
z = x+y
print(z)

[[-4 -5]
 [-5 -6]]


In [5]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [6]:
import numpy as np

x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [8]:
x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [2]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [6]:
x = np.arange(12).reshape(3,4)
print(x)
print(x[-1:,])
print(x[-1:,].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]]
(1, 4)


In [8]:
x = np.arange(4)
print(x)
print(x.flatten())

[0 1 2 3]
[0 1 2 3]


In [9]:
x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [10]:
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [11]:
x = np.arange(30).reshape(3,5,2)
print(x[1][::2][1])

[14 15]


In [12]:
x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [13]:
x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

8


In [16]:
x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(y)
print(y < 2)
print(x[y < 2, :])

[1 2 4]
[ True False False]
[[0 1]]


In [17]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [18]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [19]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [20]:
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]
